### ISSUE TITLE
oci360_run.sh: line 124: syntax error near unexpected token `>'

### ISSUE THREAD

**Issue by jomamimo** [dbarj/oci360#15]
Hi Rodrigo,

I'm trying you toll and I'm facing a small issue when running it, if I use "sh" I got a error on line 124 regarding "exec" redirect, but if I change to "bash" no issue found.

[oci360@oel8ora199 oci360_tool]$ /usr/bin/sh /u01/oci360/oci360_tool/scripts/oci360_run.sh
From this point, all the output will also be redirected to "/u01/oci360/oci360_tool/log/run.20210305151303.log".
[oci360@oel8ora199 oci360_tool]$ cd /u01/oci360/oci360_tool/log/
[oci360@oel8ora199 log]$ ls -l run.20210305151303*
-rw-r--r--. 1 oci360 users 96 Mar  5 15:13 run.20210305151303.trc
[oci360@oel8ora199 log]$ cat run.20210305151303.trc
/u01/oci360/oci360_tool/scripts/oci360_run.sh: line 124: syntax error near unexpected token `>'
[oci360@oel8ora199 log]$

**Comment by dbarj** [comment]
Hi @jomamimo. Are you running this from inside the container or from the server?

You should run this way from the server:
docker exec -it --user oci360 oci360-tool bash /u01/oci360_tool/scripts/oci360_run.sh

What is the OS full version (cat /etc/oracle-release) of your server? I will try to simulate the issue.

Thanks

**Comment by dbarj** [comment]
Sorry, I think I read your message too fast. Now I saw that the issue was solved when running as bash (expected). I will put a check on the next release to ensure the oci360_run.sh gets executed with bash instead of any other shell.
