### ISSUE TITLE
OCI360 docker install

### ISSUE THREAD

**Issue by KATTA-GITHUB** [dbarj/oci360#16]
Hi,#Rodrigo Jorge
Please help with this , i am trying install OCI36 in Oracle linux 7.9 and linux 8, i have below issue after running some time.
where as python is already installed

***********************************************
--> Finished Dependency Resolution
Error: Package: python36-dateparser-1.0.0-1.0.1.el7.noarch (ol7_developer)
           Requires: python36-regex > 2019.02.19
Error: Package: python36-dateparser-1.0.0-1.0.1.el7.noarch (ol7_developer)
           Requires: python36-tzlocal
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
+++ trap_err 33
+++ echo 'Error on line 33 of "setup_oci360.sh".'
Error on line 33 of "setup_oci360.sh".
+++ exit 1
Error while creating the oci360-tool container. Check docker logs.
********************************************************************

Regards
Srini

**Comment by dbarj** [comment]
Hi Srini. I will check it out and get back soon.

**Comment by KATTA-GITHUB** [comment]
> Hi Srini. I will check it out and get back soon.

Sure thanks much Jorge, will wait for your reply. 

this option where i am trying to install using Docker(https://github.com/dbarj/oci360/wiki/Install-OCI360) , stopped at after running around 20 min to 30 min, below is the issue. even after installing those packages package: python36-dateparser-1.0.0-1.0.1.el7.noarch & Package: python36-dateparser-1.0.0-1.0.1.el7.noarch, does not work.

*************************
--> Processing Dependency: python36-tzlocal for package: python36-dateparser-1.0.0-1.0.1.el7.noarch
---> Package python36-ply.noarch 0:3.9-2.0.1.el7 will be installed
---> Package python36-pymeeus.noarch 0:0.3.6-2.0.1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: python36-dateparser-1.0.0-1.0.1.el7.noarch (ol7_developer)
           Requires: python36-regex > 2019.02.19
Error: Package: python36-dateparser-1.0.0-1.0.1.el7.noarch (ol7_developer)
           Requires: python36-tzlocal
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
+++ trap_err 33
+++ echo 'Error on line 33 of "setup_oci360.sh".'
Error on line 33 of "setup_oci360.sh".
+++ exit 1
Error while creating the oci360-tool container. Check docker logs
********************************************************************

 Thank you
Srini

**Comment by dbarj** [comment]
Hi Sri. I've updated to the next release and fixed this issue. Please let me know if you still face any problem there.

**Comment by KATTA-GITHUB** [comment]
Thanks much for your reply Rodrigo Jorge.
That went fine and success till the end.
but some where i see error like no such container : oci360-tool not sure if this is expected error
and i have other issue while test oci-cli using root user or oci360 user from the instance , 

more details below  

1st issue ) ****************
+ cd -
/root
+ docker stop oci360-tool
Error response from daemon: No such container: oci360-tool
+ true
+ docker rm oci360-tool
Error: No such container: oci360-tool
+ true
+ docker run --name oci360-tool --restart unless-stopped -d -p 1521:1521 -e ORACLE_CHARACTERSET=AL32UTF8 -e OCI360_BRANCH=master -e OCI360_UID=54322 -v /u01/oci360_database/oradata:/opt/oracle/oradata -v /u01/oci360_database/setup:/opt/oracle/scripts/setup -v /u01:/u01 oracle/database:18.4.0-xe
09e59cea07001b31f2c15e53a91ad42cdc4ce97dc105b7489ed5ccc799713f84

I have proceeded with next steps
 - Setup oci-cli - in this step i went with Instance_principal method
 -  have updated vi /u01/.oci/config with my tenancy OCID id : and my region name
 - then i have ran below command login to my OCI web-console with account. Open the Cloud Shell and run , hopefully my account is admin account.
bash -c "$(curl -L https://raw.githubusercontent.com/dbarj/oci360/master/container/oci360_oci_cli_access.sh)"
result : 
OCI360 Instance OCID: given my created oci360 instance ocid
Dynamic Group Name for OCI360 [OCI360_DG]: 
Policy Name for OCI360 [OCI360_Policy]: 
Script finished without any error
**********************

2nd issue:
so now when i test oci-cli with below command running from my instance with root/oci360 user , have the same issue

issue : 
[root@oci360-19358 ~]# docker exec -it --user oci360 oci360-tool bash -c 'export OCI_CLI_AUTH=instance_principal; cd /tmp/; /u01/oci360_tool/app/sh/oci_json_export.sh Comp-Instances'
oci-cli not able to run "oci --cli-rc-file /dev/null iam region-subscription list". Please check error:
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /opc/v2/identity/cert.pem (Caused by NewConnectionError('<oci._vendor.urllib3.connection.HTTPConnection object at 0x7f134b548be0>: Failed to establish a new connection: [Errno 113] No route to host',))
[root@oci360-19358 ~]#

so finally i have stopped at from the doc at step 3.1 Instance_principal method (Recommended) while testing oci-cli

**Comment by dbarj** [comment]
Regarding the 1st container error, you can safely ignore it. When you run the setup script, it will drop/remove the previous containers before creating new ones. As the previous execution failed, you won't have any do drop/remove. This line of code was basically inserted if you want to redeploy/upgrade the oci360.

Regarding the "No route to host", this seems to be related with your compute instance or container not having route/egress rule/etc to the internal OCI REST API. Try to ping from the container and from the host and see if it works on both:
[root@rj-oci360-259 ~]# ping 169.254.169.254
[root@rj-oci360-259 ~]# docker exec -it --user oci360 oci360-tool bash
[oci360@94423ba89f5e /]$ ping 169.254.169.254

Regards,
RJ

**Comment by KATTA-GITHUB** [comment]
Thank you RJ , its worked.
but when i access web page using server ip https://x.x.x.x./oci360/ , 
first page showing as : 
Index of /oci360
Parent Directory
and then when i click on parent directory  it saying below
It works!  - thats it. Attached screenshots.

so how can i get full GUI webpage page to see all my OCI resources.

however i dont find any zip file generated at /u01/oci360_tool/out

Thank you
Srini
![OCI360](https://user-images.githubusercontent.com/59464149/117045894-acd97c80-ad2d-11eb-8e5e-c033bfb35dc0.GIF)
![OCI360_2](https://user-images.githubusercontent.com/59464149/117045902-ae0aa980-ad2d-11eb-8741-84316fc0d9d3.GIF)

**Comment by dbarj** [comment]
Hey man. Now you need to wait for a full execution. Add the crontab entry and wait or force a manual execution (check the wiki steps). The logs will be available in /u01/oci360_tool/log/run.*.log
