### ISSUE TITLE
installation guide request #suggestion

### ISSUE THREAD

**Issue by brokedba** [dbarj/oci360#7]
Hi  Rodrigo . 
This is maybe a newbee question but I feel like the ReadMe misses the required steps to install oco360.  I am used to oci and databases and currently have a free tier   but honestly don't haev a clue how to set this up :).
Any simple install steps and requirement available ?
thanks 
Kouss

**Comment by dbarj** [comment]
Hi KoussHD,
The steps are detailed on the github wiki page of this project, available at: https://github.com/dbarj/oci360/wiki
Have you checked that?

**Comment by brokedba** [comment]
Yes I did. I think it's not just me but People are mostly keen to see.
1- Requirement (db, installer,other)
2- Install steps (run this /that)
3-  Final checks ( check the status after install etc)

It's just my opinion and I know it's a Readme file and not a blog post but I'm sure there's a way to include relevant info without using long paragraphs .
ps: I wanted to try your package since months and I finally have time now.

**Comment by brokedba** [comment]
HI Rodrigo ,
I found it  :) , it's the link right here (was hard to spot among all the print screens ;) ). 
https://github.com/dbarj/oci360/wiki/Execution-Steps
will be closing the issue . Thanks

**Comment by dbarj** [comment]
Thanks!
